// ARCHIVO GENERADO — no editar a mano.
// Fuente: src/components/patient-guide/PatientGuide.tsx
// Regenerar: npm run voz:lexico
// Sincronía verificada en src/lib/voice/clinical-lexicon.test.ts (falla si diverge).

/** Términos del vademécum tal como aparecen en el catálogo de la Guía. */
export const TERMINOS_CATALOGO: readonly string[] = [
  "Aceite de Oliva c/Limón",
  "Aceite de Ozono",
  "Aceite de ricino",
  "Agrimony",
  "Agua mineral",
  "Aloe Vera",
  "Anti stress",
  "Antianémico",
  "Antienvejecimiento / Pro Vital",
  "Antioxidante",
  "Antiviral c/Ozono",
  "Arcilla Medicinal Bebible",
  "Arcilla Medicinal Tópica",
  "Arnigel",
  "Aspen",
  "Autovacuna",
  "Beech",
  "Biorresonancia",
  "Bioxigenación",
  "Cámara Hiperbárica",
  "Cardio Vascular",
  "Cardiovascular",
  "Células Madre Adiposa",
  "Células Madres Segment.",
  "Células Madres Sistémica",
  "Centaury",
  "CERAGEN / Masajes",
  "Cerato",
  "Cherry plum",
  "Chestnut bud",
  "Chicory",
  "Clematis",
  "Cloruro de Magnesio",
  "Colágeno",
  "Complejo B + Otro",
  "Conditioner",
  "Cosmetología / Estética",
  "Crab apple",
  "Detoxificación Alcalina",
  "Digestivo",
  "Duchas Vaginales",
  "Elm",
  "Enema Café",
  "Enema Marino",
  "Energizante",
  "Energy",
  "Esencial Oils",
  "Exosoma Serum",
  "Exosomas",
  "Factores Autólogos PRP",
  "Femenino",
  "Fiebre",
  "Gargarismos",
  "Gentian",
  "Gorse",
  "Heather",
  "Hidroterapia de Colon",
  "Hidroterapia Ionizante",
  "Holly",
  "Honeysuckle",
  "Hornbeam",
  "Immune Spray",
  "Impatiens",
  "Inmune Booster",
  "Inmune Modulador",
  "Inmuno Estimulante",
  "Inmuno Modulador",
  "Jugo de linaza",
  "Jugo de Papa Cruda",
  "Larch",
  "Láser Rojo / Infrarrojo",
  "Lavados Nasales",
  "Leche de magnesia",
  "LEM",
  "Magnesio Quelatado",
  "Masculino",
  "Mega Vitamina C",
  "MegaGH4",
  "Metabólico",
  "Mimulus",
  "Mustard",
  "Nebulización",
  "Neural",
  "Neuro Central",
  "Neuro Emocional",
  "Noni / Aloe Vera",
  "Oak",
  "Oligocell",
  "Olive",
  "Omega 3",
  "Osteo Articular",
  "Ozono",
  "Pine",
  "Plasma Marino",
  "Pre Natal",
  "Próstata",
  "Protector Solar MEL 13",
  "Quelación",
  "Red chestnut",
  "Rescue Remedy",
  "Rock rose",
  "Rock water",
  "Scleranthus",
  "Shampoo",
  "Sheet mask",
  "Shot Umbilical",
  "Spa Body Butter",
  "Spa Body Scroob",
  "Spa Foot",
  "Spa Massage",
  "Star of Bethlehem",
  "StemCell Enhancer",
  "Sweet chestnut",
  "Telomeros",
  "Terapia BioCelular",
  "Transfer Tri Factor",
  "Utilizar tintes sin amoníaco",
  "Vervain",
  "Vine",
  "Vit C c/Zinc",
  "Vit E c/Selenio",
  "Walnut",
  "Water violet",
  "White chestnut",
  "Wild oat",
  "Wild rose",
  "Willow",
  "Zinc Quelatado",
];
