// ARCHIVO GENERADO — no editar a mano.
// Fuente: src/components/patient-guide/PatientGuide.tsx
// Regenerar: npm run voz:lexico
// Sincronía verificada en src/lib/voice/clinical-lexicon.test.ts (falla si diverge).

/** Términos del vademécum tal como aparecen en el catálogo de la Guía. */
export const TERMINOS_CATALOGO: readonly string[] = [
  "Aceite de Oliva c/Limón",
  "Aceite de Ozono",
  "Aceite de ricino",
  "Adrenales",
  "Agrimony",
  "Agua mineral",
  "Aloe Vera",
  "Anti stress",
  "Antianémico",
  "Antienvejecimiento / Pro Vital",
  "Antioxidante",
  "Antiviral c/Ozono",
  "Arcilla Medicinal Bebible",
  "Arcilla Medicinal Tópica",
  "Arnigel",
  "Articular",
  "Aspen",
  "Autovacuna",
  "Beech",
  "Biorresonancia",
  "Bioxigenación",
  "Cámara Hiperbárica",
  "Cardio Vascular",
  "Cardiovascular",
  "Células Madre Adiposa",
  "Células Madres Segment.",
  "Células Madres Sistémica",
  "Centaury",
  "CERAGEN / Masajes",
  "Cerato",
  "Cerebro",
  "Cherry plum",
  "Chestnut bud",
  "Chicory",
  "Circulación Arterial",
  "Circulación Micro",
  "Circulación Venosa",
  "Clematis",
  "Cloruro de Magnesio",
  "Colágeno",
  "Complejo B + Otro",
  "Conditioner",
  "Corazón",
  "Cosmetología / Estética",
  "Crab apple",
  "Detoxificación Alcalina",
  "Digestivo",
  "Disco",
  "Duchas Vaginales",
  "Elm",
  "Enema Café",
  "Enema Marino",
  "Energética General",
  "Energizante",
  "Energy",
  "Esencial Oils",
  "Estreptococo",
  "Exosoma Serum",
  "Exosomas",
  "Factores Autólogos PRP",
  "Femenino",
  "Fiebre",
  "Gargarismos",
  "Gastrointestinal",
  "Gentian",
  "Gorse",
  "Heather",
  "Hidroterapia de Colon",
  "Hidroterapia Ionizante",
  "Hígado",
  "Holly",
  "Honeysuckle",
  "Hornbeam",
  "Huesos",
  "Immune Spray",
  "Impatiens",
  "Inmune Booster",
  "Inmune Modulador",
  "Inmuno Estimulante",
  "Inmuno Modulador",
  "Jugo de linaza",
  "Jugo de Papa Cruda",
  "Larch",
  "Láser Rojo / Infrarrojo",
  "Lavados Nasales",
  "Leche de magnesia",
  "LEM",
  "Linfático",
  "Magnesio Quelatado",
  "Masculino",
  "Médula Espinal",
  "Médula Ósea",
  "Mega Vitamina C",
  "MegaGH4",
  "Metabólico",
  "Mimulus",
  "Mucosa",
  "Musculatura",
  "Mustard",
  "Nebulización",
  "Neural",
  "Neuro Central",
  "Neuro Emocional",
  "Noni / Aloe Vera",
  "Oak",
  "Oligocell",
  "Olive",
  "Omega 3",
  "Osteo Articular",
  "Ozono",
  "Páncreas",
  "Piel",
  "Pine",
  "Placenta Embrionaria",
  "Plasma Marino",
  "Pre Natal",
  "Próstata",
  "Protector Solar MEL 13",
  "Psicoestabilizante",
  "Quelación",
  "Red chestnut",
  "Reproductivo Femenino",
  "Reproductivo Masculino",
  "Rescue Remedy",
  "Respiratorio",
  "Riñón",
  "Rock rose",
  "Rock water",
  "Scleranthus",
  "Sexual Femenina",
  "Sexual Masculina",
  "Shampoo",
  "Sheet mask",
  "Shot Umbilical",
  "Spa Body Butter",
  "Spa Body Scroob",
  "Spa Foot",
  "Spa Massage",
  "Star of Bethlehem",
  "StemCell Enhancer",
  "Sweet chestnut",
  "Telomeros",
  "Terapia BioCelular",
  "Tiroides",
  "Transfer Tri Factor",
  "Utilizar tintes sin amoníaco",
  "Vacuna Antivejez",
  "Vejiga",
  "Vértigo",
  "Vervain",
  "Vías Biliares",
  "Vine",
  "Visión",
  "Vit C c/Zinc",
  "Vit E c/Selenio",
  "Walnut",
  "Water violet",
  "White chestnut",
  "Wild oat",
  "Wild rose",
  "Willow",
  "Zinc Quelatado",
];
